"""Curated treatment guidance for the 6 tomato disease classes the model
classifies (see build brief §6), in all 3 supported languages. This is the
only place this content is authored — TreatmentRecord rows are seeded from
here, and the API only ever reads what's already in the table (FR-TG-01)."""

TREATMENT_SEED: list[dict] = [
    # ---------------------------------------------------------------- healthy
    {
        "disease_class": "healthy",
        "language": "en",
        "symptoms": "No visible disease symptoms. Leaves are uniform green with no lesions, curling, or discoloration.",
        "immediate_actions": [
            "Continue your regular watering and fertilizer schedule.",
            "Keep monitoring leaves weekly for early signs of disease.",
            "Maintain good spacing and airflow between plants.",
        ],
        "prevention": "Rotate crops each season, use certified disease-free seedlings, and avoid overhead irrigation in humid weather to keep plants healthy.",
        "indicative_cost_min": 0,
        "indicative_cost_max": 0,
    },
    {
        "disease_class": "healthy",
        "language": "te",
        "symptoms": "కనిపించే వ్యాధి లక్షణాలు లేవు. ఆకులు మచ్చలు, ముడత లేదా రంగు మార్పు లేకుండా ఏకరీతిగా ఆకుపచ్చగా ఉన్నాయి.",
        "immediate_actions": [
            "మీ సాధారణ నీటిపారుదల మరియు ఎరువుల షెడ్యూల్‌ను కొనసాగించండి.",
            "వ్యాధి ప్రారంభ సంకేతాల కోసం ప్రతి వారం ఆకులను పరిశీలించండి.",
            "మొక్కల మధ్య మంచి ఖాళీ మరియు గాలి ప్రసరణను కాపాడండి.",
        ],
        "prevention": "ప్రతి సీజన్‌లో పంట మార్పిడి చేయండి, ధృవీకరించబడిన వ్యాధి రహిత మొక్కలను వాడండి, తేమ వాతావరణంలో పైనుండి నీరు పెట్టడం మానుకోండి.",
        "indicative_cost_min": 0,
        "indicative_cost_max": 0,
    },
    {
        "disease_class": "healthy",
        "language": "hi",
        "symptoms": "कोई दिखाई देने वाला रोग लक्षण नहीं है। पत्तियाँ बिना दाग, मरोड़ या रंग बदले हरी और एक समान हैं।",
        "immediate_actions": [
            "अपनी सामान्य सिंचाई और खाद की समय-सारणी जारी रखें।",
            "रोग के शुरुआती संकेतों के लिए हर हफ्ते पत्तियों की जाँच करें।",
            "पौधों के बीच अच्छी दूरी और हवा का आवागमन बनाए रखें।",
        ],
        "prevention": "हर मौसम में फसल चक्र अपनाएँ, प्रमाणित रोग-मुक्त पौध का उपयोग करें, और नमी वाले मौसम में ऊपर से सिंचाई करने से बचें।",
        "indicative_cost_min": 0,
        "indicative_cost_max": 0,
    },
    # ----------------------------------------------------------- early_blight
    {
        "disease_class": "early_blight",
        "language": "en",
        "symptoms": "Dark brown spots with concentric rings (target-like) on older, lower leaves first; yellowing around the spots; leaves eventually dry and drop.",
        "immediate_actions": [
            "Remove and destroy affected lower leaves immediately.",
            "Spray a mancozeb or chlorothalonil-based fungicide within 24 hours.",
            "Avoid wetting leaves while watering; water at the base.",
            "Repeat fungicide spray every 7-10 days until symptoms stop spreading.",
        ],
        "prevention": "Stake or cage plants to keep leaves off the soil, mulch to prevent soil splash onto lower leaves, and rotate away from tomato/potato family for at least 2 seasons.",
        "indicative_cost_min": 350,
        "indicative_cost_max": 600,
    },
    {
        "disease_class": "early_blight",
        "language": "te",
        "symptoms": "పాత, కింది ఆకులపై ముందుగా గోధుమ రంగు మచ్చలు గుండ్రని వలయాలతో (టార్గెట్ లాగా) కనిపిస్తాయి; మచ్చల చుట్టూ పసుపు రంగు; చివరికి ఆకులు ఎండి రాలిపోతాయి.",
        "immediate_actions": [
            "ప్రభావితమైన కింది ఆకులను వెంటనే తీసివేసి నాశనం చేయండి.",
            "24 గంటల్లో మాంకోజెబ్ లేదా క్లోరోథలోనిల్ ఆధారిత శిలీంద్రనాశినిని పిచికారీ చేయండి.",
            "నీరు పెట్టేటప్పుడు ఆకులు తడవకుండా చూడండి; మొదట్లో నీరు పెట్టండి.",
            "లక్షణాలు ఆగే వరకు ప్రతి 7-10 రోజులకు మళ్ళీ పిచికారీ చేయండి.",
        ],
        "prevention": "ఆకులు నేలను తాకకుండా మొక్కలను కర్రలతో కట్టండి, కింది ఆకులపై మట్టి చిమ్మకుండా మల్చింగ్ వాడండి, కనీసం 2 సీజన్ల పాటు టమాటా/బంగాళదుంప కుటుంబం నుండి పంట మార్చండి.",
        "indicative_cost_min": 350,
        "indicative_cost_max": 600,
    },
    {
        "disease_class": "early_blight",
        "language": "hi",
        "symptoms": "पुरानी, निचली पत्तियों पर पहले गहरे भूरे रंग के धब्बे गोलाकार छल्लों के साथ (निशाने जैसे) दिखते हैं; धब्बों के चारों ओर पीलापन; अंत में पत्तियाँ सूखकर गिर जाती हैं।",
        "immediate_actions": [
            "प्रभावित निचली पत्तियों को तुरंत हटाकर नष्ट कर दें।",
            "24 घंटों के भीतर मैंकोज़ेब या क्लोरोथैलोनिल आधारित फफूंदनाशक का छिड़काव करें।",
            "सिंचाई करते समय पत्तियों को गीला होने से बचाएँ; जड़ के पास पानी दें।",
            "लक्षण फैलना बंद होने तक हर 7-10 दिन में छिड़काव दोहराएँ।",
        ],
        "prevention": "पत्तियों को मिट्टी से दूर रखने के लिए पौधों को सहारा दें, निचली पत्तियों पर मिट्टी के छींटे रोकने के लिए मल्चिंग करें, और कम से कम 2 मौसम तक टमाटर/आलू परिवार से फसल चक्र बदलें।",
        "indicative_cost_min": 350,
        "indicative_cost_max": 600,
    },
    # ------------------------------------------------------------ late_blight
    {
        "disease_class": "late_blight",
        "language": "en",
        "symptoms": "Dark, water-soaked patches on leaves; white fungal growth on the underside of leaves in humid weather; brown lesions spreading to stems and fruit.",
        "immediate_actions": [
            "Remove and burn visibly infected leaves and fruit.",
            "Spray a copper-based fungicide within 24 hours.",
            "Avoid overhead irrigation until the spray has dried.",
            "Improve spacing between plants for airflow.",
        ],
        "prevention": "Rotate crops away from tomato/potato family for 2 seasons, use certified disease-free seedlings, and apply a preventive copper spray before the monsoon onset.",
        "indicative_cost_min": 450,
        "indicative_cost_max": 750,
    },
    {
        "disease_class": "late_blight",
        "language": "te",
        "symptoms": "ఆకులపై నీటితో తడిసిన ముదురు మచ్చలు; తేమ వాతావరణంలో ఆకుల అడుగుభాగాన తెల్లని శిలీంధ్ర పెరుగుదల; గోధుమ రంగు గాయాలు కాండం మరియు కాయలకు వ్యాపిస్తాయి.",
        "immediate_actions": [
            "కంటికి కనిపించే వ్యాధిగ్రస్త ఆకులు మరియు కాయలను తీసివేసి కాల్చివేయండి.",
            "24 గంటల్లో రాగి ఆధారిత శిలీంద్రనాశినిని పిచికారీ చేయండి.",
            "పిచికారీ ఆరిపోయేవరకు పైనుండి నీరు పెట్టడం మానుకోండి.",
            "గాలి ప్రసరణ కోసం మొక్కల మధ్య ఖాళీని పెంచండి.",
        ],
        "prevention": "2 సీజన్ల పాటు టమాటా/బంగాళదుంప కుటుంబం నుండి పంట మార్చండి, ధృవీకరించబడిన వ్యాధి రహిత మొక్కలను వాడండి, రుతుపవనాలకు ముందు నివారణ రాగి పిచికారీ చేయండి.",
        "indicative_cost_min": 450,
        "indicative_cost_max": 750,
    },
    {
        "disease_class": "late_blight",
        "language": "hi",
        "symptoms": "पत्तियों पर पानी से भीगे गहरे धब्बे; नमी वाले मौसम में पत्तियों के नीचे की ओर सफेद फफूंद; भूरे घाव तने और फल तक फैलते हैं।",
        "immediate_actions": [
            "दिखने वाली संक्रमित पत्तियों और फलों को हटाकर जला दें।",
            "24 घंटों के भीतर तांबा (कॉपर) आधारित फफूंदनाशक का छिड़काव करें।",
            "छिड़काव सूखने तक ऊपर से सिंचाई न करें।",
            "हवा के आवागमन के लिए पौधों के बीच दूरी बढ़ाएँ।",
        ],
        "prevention": "2 मौसम तक टमाटर/आलू परिवार से फसल चक्र बदलें, प्रमाणित रोग-मुक्त पौध का उपयोग करें, और मानसून शुरू होने से पहले निवारक तांबा छिड़काव करें।",
        "indicative_cost_min": 450,
        "indicative_cost_max": 750,
    },
    # ------------------------------------------------------------ target_spot
    {
        "disease_class": "target_spot",
        "language": "en",
        "symptoms": "Small water-soaked spots that enlarge into brown lesions with faint concentric rings, often with a yellow halo; appears on leaves, stems, and fruit, usually starting on older leaves.",
        "immediate_actions": [
            "Remove and destroy heavily spotted leaves.",
            "Apply a chlorothalonil or azoxystrobin-based fungicide within 24-48 hours.",
            "Avoid working in the field when foliage is wet to prevent spreading spores.",
            "Repeat fungicide application every 7-14 days as needed.",
        ],
        "prevention": "Ensure good plant spacing for airflow, avoid overhead watering, and remove crop debris after harvest since the fungus survives on plant residue.",
        "indicative_cost_min": 400,
        "indicative_cost_max": 700,
    },
    {
        "disease_class": "target_spot",
        "language": "te",
        "symptoms": "చిన్న నీటితో తడిసిన మచ్చలు గోధుమ రంగు గాయాలుగా మారి, తేలికపాటి గుండ్రని వలయాలతో, తరచుగా పసుపు రంగు అంచుతో కనిపిస్తాయి; ఆకులు, కాండం, కాయలపై సాధారణంగా పాత ఆకులతో మొదలవుతుంది.",
        "immediate_actions": [
            "ఎక్కువగా మచ్చలు ఉన్న ఆకులను తీసివేసి నాశనం చేయండి.",
            "24-48 గంటల్లో క్లోరోథలోనిల్ లేదా అజోక్సిస్ట్రోబిన్ ఆధారిత శిలీంద్రనాశినిని వాడండి.",
            "బీజాంశాలు వ్యాపించకుండా ఆకులు తడిగా ఉన్నప్పుడు పొలంలో పని చేయడం మానుకోండి.",
            "అవసరమైతే ప్రతి 7-14 రోజులకు మళ్ళీ పిచికారీ చేయండి.",
        ],
        "prevention": "గాలి ప్రసరణ కోసం మొక్కల మధ్య మంచి ఖాళీ ఉంచండి, పైనుండి నీరు పెట్టడం మానుకోండి, కోత తర్వాత పంట అవశేషాలను తీసివేయండి ఎందుకంటే శిలీంధ్రం వాటిపై జీవిస్తుంది.",
        "indicative_cost_min": 400,
        "indicative_cost_max": 700,
    },
    {
        "disease_class": "target_spot",
        "language": "hi",
        "symptoms": "छोटे पानी से भीगे धब्बे बड़े होकर भूरे घावों में बदल जाते हैं जिनमें हल्के गोलाकार छल्ले होते हैं, अक्सर पीले घेरे के साथ; पत्तियों, तनों और फलों पर, आमतौर पर पुरानी पत्तियों से शुरू होता है।",
        "immediate_actions": [
            "अधिक धब्बे वाली पत्तियों को हटाकर नष्ट कर दें।",
            "24-48 घंटों के भीतर क्लोरोथैलोनिल या एज़ोक्सीस्ट्रोबिन आधारित फफूंदनाशक का प्रयोग करें।",
            "बीजाणु फैलने से रोकने के लिए पत्तियाँ गीली होने पर खेत में काम करने से बचें।",
            "आवश्यकतानुसार हर 7-14 दिन में छिड़काव दोहराएँ।",
        ],
        "prevention": "हवा के आवागमन के लिए पौधों के बीच अच्छी दूरी रखें, ऊपर से सिंचाई से बचें, और कटाई के बाद फसल के अवशेष हटा दें क्योंकि यह फफूंद उन पर जीवित रहती है।",
        "indicative_cost_min": 400,
        "indicative_cost_max": 700,
    },
    # ------------------------------------------------- yellow_leaf_curl_virus
    {
        "disease_class": "yellow_leaf_curl_virus",
        "language": "en",
        "symptoms": "Upward curling and cupping of young leaves, yellowing along leaf margins and between veins, stunted plant growth, and reduced flowering/fruit set.",
        "immediate_actions": [
            "Uproot and destroy severely affected plants to reduce virus spread.",
            "Control whitefly (the carrier insect) with a neem-oil or imidacloprid spray.",
            "Install yellow sticky traps around the field border to catch whiteflies.",
            "Cover young seedlings with insect-proof netting where possible.",
        ],
        "prevention": "Use virus-resistant tomato varieties next season, keep field borders free of weeds that host whitefly, and avoid planting near infected fields.",
        "indicative_cost_min": 300,
        "indicative_cost_max": 550,
    },
    {
        "disease_class": "yellow_leaf_curl_virus",
        "language": "te",
        "symptoms": "లేత ఆకులు పైకి ముడుచుకుని కప్పు ఆకారంలో మారడం, ఆకు అంచుల వెంబడి మరియు నరాల మధ్య పసుపు రంగు, మొక్క ఎదుగుదల ఆగిపోవడం, పూత/కాయ తగ్గడం.",
        "immediate_actions": [
            "వ్యాధి వ్యాప్తిని తగ్గించడానికి తీవ్రంగా ప్రభావితమైన మొక్కలను పీకి నాశనం చేయండి.",
            "వాహక కీటకమైన తెల్లదోమను వేప నూనె లేదా ఇమిడాక్లోప్రిడ్ పిచికారీతో నియంత్రించండి.",
            "తెల్లదోమలను పట్టుకోవడానికి పొలం చుట్టూ పసుపు జిగురు ఉచ్చులు ఏర్పాటు చేయండి.",
            "వీలైతే లేత మొక్కలను కీటక నిరోధక వలతో కప్పండి.",
        ],
        "prevention": "వచ్చే సీజన్‌లో వైరస్ నిరోధక టమాటా రకాలను వాడండి, తెల్లదోమకు ఆశ్రయమిచ్చే కలుపు మొక్కలను పొలం అంచుల్లో లేకుండా చూడండి, వ్యాధిగ్రస్త పొలాల దగ్గర నాటడం మానుకోండి.",
        "indicative_cost_min": 300,
        "indicative_cost_max": 550,
    },
    {
        "disease_class": "yellow_leaf_curl_virus",
        "language": "hi",
        "symptoms": "नई पत्तियों का ऊपर की ओर मुड़ना और कप जैसा आकार लेना, पत्ती के किनारों और शिराओं के बीच पीलापन, पौधे की बढ़वार रुकना, और फूल/फल कम आना।",
        "immediate_actions": [
            "वायरस फैलने से रोकने के लिए गंभीर रूप से प्रभावित पौधों को उखाड़कर नष्ट कर दें।",
            "वाहक कीट सफेद मक्खी को नीम तेल या इमिडाक्लोप्रिड छिड़काव से नियंत्रित करें।",
            "सफेद मक्खियों को पकड़ने के लिए खेत की सीमा पर पीले चिपचिपे जाल लगाएँ।",
            "जहाँ संभव हो, नई पौध को कीट-रोधी जाली से ढकें।",
        ],
        "prevention": "अगले मौसम में वायरस-प्रतिरोधी टमाटर किस्मों का उपयोग करें, खेत की सीमाओं को सफेद मक्खी को आश्रय देने वाले खरपतवार से मुक्त रखें, और संक्रमित खेतों के पास बुवाई से बचें।",
        "indicative_cost_min": 300,
        "indicative_cost_max": 550,
    },
    # -------------------------------------------------------------- mosaic_virus
    {
        "disease_class": "mosaic_virus",
        "language": "en",
        "symptoms": "Mottled light and dark green patches (mosaic pattern) on leaves, leaf distortion or fern-like narrowing, stunted growth, and mottled or distorted fruit.",
        "immediate_actions": [
            "Remove and destroy infected plants immediately — this virus spreads easily by touch and tools.",
            "Wash hands and disinfect tools (with a 10% bleach or milk solution) after handling infected plants.",
            "Avoid working with plants when leaves are wet.",
            "Do not use tobacco products near plants (the virus can spread from tobacco).",
        ],
        "prevention": "Use certified virus-free seed, control aphids which can spread the virus, and avoid handling healthy plants right after infected ones.",
        "indicative_cost_min": 250,
        "indicative_cost_max": 500,
    },
    {
        "disease_class": "mosaic_virus",
        "language": "te",
        "symptoms": "ఆకులపై లేత మరియు ముదురు ఆకుపచ్చ మచ్చలు (మొజాయిక్ నమూనా), ఆకు వైకల్యం లేదా ఫెర్న్ లాగా సన్నబడటం, ఎదుగుదల ఆగిపోవడం, కాయలపై మచ్చలు లేదా వైకల్యం.",
        "immediate_actions": [
            "వైరస్‌గ్రస్త మొక్కలను వెంటనే తీసివేసి నాశనం చేయండి — ఇది తాకడం మరియు పనిముట్ల ద్వారా సులభంగా వ్యాపిస్తుంది.",
            "వ్యాధిగ్రస్త మొక్కలను ముట్టుకున్న తర్వాత చేతులు కడుక్కుని, పనిముట్లను (10% బ్లీచ్ లేదా పాల ద్రావణంతో) శుభ్రం చేయండి.",
            "ఆకులు తడిగా ఉన్నప్పుడు మొక్కలతో పని చేయడం మానుకోండి.",
            "మొక్కల దగ్గర పొగాకు ఉత్పత్తులను వాడవద్దు (వైరస్ పొగాకు నుండి వ్యాపించవచ్చు).",
        ],
        "prevention": "ధృవీకరించబడిన వైరస్ రహిత విత్తనాలను వాడండి, వైరస్‌ను వ్యాప్తి చేసే పేనుబంక (అఫిడ్స్)ను నియంత్రించండి, వ్యాధిగ్రస్త మొక్కలను తాకిన వెంటనే ఆరోగ్యకరమైన మొక్కలను తాకవద్దు.",
        "indicative_cost_min": 250,
        "indicative_cost_max": 500,
    },
    {
        "disease_class": "mosaic_virus",
        "language": "hi",
        "symptoms": "पत्तियों पर हल्के और गहरे हरे धब्बे (मोज़ेक पैटर्न), पत्ती का विकृत होना या फर्न जैसा पतला होना, बढ़वार रुकना, और फलों पर धब्बे या विकृति।",
        "immediate_actions": [
            "संक्रमित पौधों को तुरंत हटाकर नष्ट कर दें — यह वायरस छूने और औजारों से आसानी से फैलता है।",
            "संक्रमित पौधों को छूने के बाद हाथ धोएँ और औजारों को (10% ब्लीच या दूध के घोल से) कीटाणुरहित करें।",
            "पत्तियाँ गीली होने पर पौधों के साथ काम करने से बचें।",
            "पौधों के पास तंबाकू उत्पादों का उपयोग न करें (वायरस तंबाकू से फैल सकता है)।",
        ],
        "prevention": "प्रमाणित वायरस-मुक्त बीज का उपयोग करें, वायरस फैलाने वाले माहू (एफिड्स) को नियंत्रित करें, और संक्रमित पौधों को छूने के तुरंत बाद स्वस्थ पौधों को न छुएँ।",
        "indicative_cost_min": 250,
        "indicative_cost_max": 500,
    },
]

DISEASE_CLASSES = [
    "healthy",
    "early_blight",
    "late_blight",
    "target_spot",
    "yellow_leaf_curl_virus",
    "mosaic_virus",
]
